/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection */

#ifndef _Included_edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection
#define _Included_edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection
 * Method:    computeOpenCL
 * Signature: ([FII[D[DFI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection_computeOpenCL
  (JNIEnv *, jobject, jfloatArray, jint, jint, jdoubleArray, jdoubleArray, jfloat, jint);

/*
 * Class:     edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection
 * Method:    testPassing
 * Signature: ([FII[D[DFI)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_monash_fit_eduard_grid_operator_lic_OpenCLConnection_testPassing
  (JNIEnv *, jobject, jfloatArray, jint, jint, jdoubleArray, jdoubleArray, jfloat, jint);

#ifdef __cplusplus
}
#endif
#endif
